services:
  # Zookeeper для Kafka
  zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      ZOO_ENABLE_AUTH: "no"
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  # Одноузловой Kafka
  kafka:
    image: bitnami/kafka:3.5
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: ["--config", "/etc/otel-collector-config.yaml"]
    volumes:
      - ./monitoring/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"
    depends_on:
      - kafka

  # Сервис market-data-collector
  market-data-collector:
    build:
      context: ../services/market-data-collector
      dockerfile: Dockerfile
    image: market-data-collector:latest
    volumes:
      # Монтируем конфиг внутрь контейнера
      - ../services/market-data-collector/config:/config:ro
    command: ["--config", "/config/config.yaml"]
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - otel-collector
