service_name: "preprocessor"
service_version: "v1.0.0"

kafka:
  brokers:
    - "kafka:9092"
  raw_topic: "marketdata.raw"
  orderbook_topic: "marketdata.orderbook"
  aggregation_topics:
    - interval: "1m"
      topic: "marketdata.agg.1m"
    - interval: "5m"
      topic: "marketdata.agg.5m"
    - interval: "15m"
      topic: "marketdata.agg.15m"
    - interval: "1h"
      topic: "marketdata.agg.1h"
  group_id: "preprocessor-group"
  backoff:
    initial_interval: "1s"
    max_interval: "30s"
    max_elapsed_time: "5m"

redis:
  address: "redis:6379"
  password: ""
  db: 0
  ttl: "5m"

telemetry:
  otel_endpoint: "otel-collector:4317"
  insecure: false

logging:
  level: "info"
  dev_mode: false

http:
  port: 8090
