# // github.com/YaganovValera/analytics-system/services/preprocessor/config/config.yaml


# ------------------------------------------------------------------------------
#  Preprocessor — основной конфигурационный файл
# ------------------------------------------------------------------------------

service_name:    "preprocessor"
service_version: "v1.0.0"

# ------------------------------------------------------------------------------
# Kafka Consumer
# ------------------------------------------------------------------------------
kafka:
  brokers:
    - "kafka:9092"
  version: "2.8.0"
  group_id: "preprocessor"
  raw_topic: "marketdata.raw"
  output_topic_prefix: "candles"
  backoff:
    initial_interval: "1s"
    max_interval: "30s"
    max_elapsed_time: "5m"

# ------------------------------------------------------------------------------
# Redis (PartialBarStorage)
# ------------------------------------------------------------------------------
redis:
  addr: "redis:6379"
  password: ""
  db: 0

# ------------------------------------------------------------------------------
# TimescaleDB (FlushSink)
# ------------------------------------------------------------------------------
timescaledb:
  dsn: "postgres://user:pass@timescaledb:5432/analytics?sslmode=disable"
  migrations_dir: "/app/migrations/timescaledb"

# ------------------------------------------------------------------------------
# OpenTelemetry
# ------------------------------------------------------------------------------
telemetry:
  otel_endpoint: "otel-collector:4317"
  insecure: true

# ------------------------------------------------------------------------------
# Logging
# ------------------------------------------------------------------------------
logging:
  level: "info"
  dev_mode: false

# ------------------------------------------------------------------------------
# HTTP Server (metrics + health)
# ------------------------------------------------------------------------------
http:
  port: 8081
  read_timeout: "10s"
  write_timeout: "15s"
  idle_timeout: "60s"
  shutdown_timeout: "5s"
  metrics_path: "/metrics"
  healthz_path: "/healthz"
  readyz_path: "/readyz"

# ------------------------------------------------------------------------------
# Intervals (OHLCV)
# ------------------------------------------------------------------------------
intervals:
  - "1m"
  - "5m"
  - "15m"
  - "1h"
  - "4h"
  - "1d"
