# services/preprocessor/config/config.yaml
service_name:    "preprocessor"
service_version: "v1.0.0"

binance:
  raw_topic: "marketdata.raw"
  symbols:
    - "btcusdt@trade"
    - "ethusdt@trade"
  backoff:
    initial_interval:   "1s"
    randomization_factor: 0.5
    multiplier:          2.0
    max_interval:        "30s"
    max_elapsed_time:    "5m"

kafka:
  brokers:
    - "kafka:9092"
  raw_topic:   "marketdata.raw"
  timeout:     "15s"
  acks:        "all"
  compression: "none"
  backoff:
    initial_interval:   "1s"
    randomization_factor: 0.5
    multiplier:          2.0
    max_interval:        "30s"
    max_elapsed_time:    "5m"

postgres:
  dsn:              "postgres://user:pass@postgres:5432/analytics?sslmode=disable"
  max_open_conns:   25
  max_idle_conns:   10
  conn_max_lifetime: "1h"

telemetry:
  otel_endpoint: "otel-collector:4317"
  insecure:      false

logging:
  level:    "info"
  dev_mode: false

http:
  port:              8090
  read_timeout:      "10s"
  write_timeout:     "15s"
  idle_timeout:      "60s"
  shutdown_timeout:  "5s"
  metrics_path:      "/metrics"
  healthz_path:      "/healthz"
  readyz_path:       "/readyz"
