# services/market-data-collector/config/config.yaml

service_name:    "market-data-collector"
service_version: "v1.0.0"

# ------------------------------------------------------------------------------
#  Binance WebSocket (pkg/binance.Config)
# ------------------------------------------------------------------------------
binance:
  ws_url: "wss://stream.binance.com:9443/ws"
  streams:
    - "btcusdt@trade"
    - "ethusdt@depth"
  read_timeout:      "30s"
  subscribe_timeout: "5s"
  buffer_size:       10000
  backoff:
    initial_interval: "1s"
    max_interval:     "30s"
    max_elapsed_time: "5m"

# ------------------------------------------------------------------------------
#  Kafka Producer (KafkaConfig)
# ------------------------------------------------------------------------------
kafka:
  brokers:
    - "kafka:9092"
  required_acks:     "all"      # all | leader | none
  timeout:           "15s"
  compression:       "none"     # none | gzip | snappy | lz4 | zstd
  flush_frequency:   "0s"
  flush_messages:    0
  backoff:
    initial_interval: "1s"
    max_interval:     "30s"
    max_elapsed_time: "5m"
  raw_topic:         "marketdata.raw"
  orderbook_topic:   "marketdata.orderbook"

# ------------------------------------------------------------------------------
#  OpenTelemetry (telemetry.Config)
# ------------------------------------------------------------------------------
telemetry:
  endpoint: "otel-collector:4317"
  insecure: true
  service_name:    "market-data-collector"
  service_version: "v1.0.0"
  # остальные параметры (reconnect_period, timeout, sampler_ratio) берутся из defaults

# ------------------------------------------------------------------------------
#  Logging (logger.Config)
# ------------------------------------------------------------------------------
logging:
  level:    "info"
  dev_mode: false
  # format — по умолчанию "console"

# ------------------------------------------------------------------------------
#  HTTP/metrics-server (httpserver.Config)
# ------------------------------------------------------------------------------
http:
  port:              8080
  read_timeout:      "10s"
  write_timeout:     "15s"
  idle_timeout:      "60s"
  shutdown_timeout:  "5s"
  metrics_path:      "/metrics"
  healthz_path:      "/healthz"
  readyz_path:       "/readyz"
